version: 2

sources:
  - name: raw
    schema: public    # the schema that pipeline will write into
    description: "Raw tables loaded by the Airflow pipeline from S3 via Redshift COPY command"
    tables:
      - name: stock_prices
        description: "Daily OHLCV stock prices"
        columns:
          - name: symbol
            description: "Ticker symbol"
          - name: date
            description: "Trading date"
          - name: open_price
            description: "Opening price for the trading day/period"
          - name: high
            description: "Highest price for the trading day/period"
          - name: low
            description: "Lowest price for the trading day/period"
          - name: close_price
            description: "Closing price for the trading day/period"
          - name: volume
            description: "# of shares traded for the day/period"

      - name: dim_metadata
        description: "Company dimension: name and sector"
        columns:
          - name: symbol
            description: "Ticker symbol - primary key"
          - name: company_name
            description: "Legal entity name of the company"
          - name: sector
            description: "GICS sector classification"

      - name: dim_date
        description: "Date dimension"
        columns:
          - name: date
            description: "Calendar date - primary key"
          - name: day
            description: "Day of the month (1-31)"
          - name: month
            description: "Month of the year (1-12)"
          - name: year
            description: "Year"
          - name: quarter
            description: "Quarter of the year (1-4)"
          - name: day_of_week
            description: "Day of the week (0=Monday, 6=Sunday)"
          - name: week_of_year
            description: "ISO week number of the year (1-53)"

      - name: fundamentals
        description: "Company fundamentals data"
        columns:
          - name: symbol
            description: "Ticker symbol - foreign key to dim_metadata"
          - name: period_end_date
            description: "End date of the reporting period (YYYY-MM-DD)"
          - name: form_type
            description: "Type of SEC filing (e.g. 10-K, 10-Q)"
          - name: metric
            description: "Financial metrics"
          - name: value
            description: "Financial metric value"
          - name: unit
            description: "Financial metric units"
          - name: filed_date
            description: "Date that the report was filed into SEC database (YYYY-MM-DD)"

      - name: macros
        description: "Macroeconomic data"
        columns:
          - name: series_id
            description: "FRED series identifier, basically the macroeconomic metrics"
          - name: date
            description: "Date or period which series_id represents"
          - name: value
            description: "The actual value of that macroeconomic metric"

      - name: news_sentiment
        description: "News sentiment for the particular stocks"
        columns:
          - name: symbol
            description: "Ticker symbol"
          - name: date
            description: "Date that the news posted"
          - name: headline
            description: "The short description of the news"
          - name: sentiment_score
            description: "Calculated sentiment score of the news"
          - name: source
            description: "Resource of the news"
          - name: url
            description: "URL link to the news"